name: test
uid: uuid-of-etcd-resource
serviceName: test 
configMapName: test

replicas: 1

tlsServerSecret: etcd-server-tls
tlsClientSecret: etcd-client-tls
tlsCASecret: ca-etcd
annotations: {}
labels: {}

etcd:
  initialClusterToken: initial
  initialClusterState: new
  enableTLS: false
  pullPolicy: IfNotPresent
  metrics: basic
  clientPort: 2379
  serverPort: 2380
  resources:
    limits:
      cpu: 100m
      memory: 512Gi
    requests:
      cpu: 50m
      memory: 128Mi
  #username: username
  #password: password

backup:
  pullPolicy: IfNotPresent
  snapstoreTempDir: "/tmp"
  etcdConnectionTimeout: 30
  etcdQuotaBytes: 8Gi
  garbageCollectionPolicy: LimitBased
  maxBackups: 7
  resources:
    limits:
      cpu: 100m
      memory: 512Gi
    requests:
      cpu: 50m
      memory: 128Mi

volumeClaimTemplateName: test
storageClass: ""
storageCapacity: 16Gi

store:
  storageProvider: ""
  storePrefix: ""
  storageContainer: ""